config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	        sessions: 'users/sessions',
	        registrations: 'users/registrations'
	      }
  resources :users do
    resource :favorites, only: [:show]
		resources :carts, only: [:show]
		resources :orders, only: [:index, :show, :new, :create]
  end
	get 'users/:id/receivers', to: 'users#receivers', as: "user_receivers"
  get 'users/:id/edit_receivers', to: 'users#edit_receivers', as: "edit_user_receivers"

  get 'contacts/about', to: 'contacts#about'
  get 'contacts/term', to: 'contacts#term'
  get 'contacts/recieve', to: 'contacts#recieve'
  resources :contacts

  root 'items#top'
  get 'items/about', to: 'items#about'
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  post '/add_cart_item/:item_id', to: "carts#add_cart_item", as: "add_cart_item"
  patch  '/update_cart_item/:id', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/delete_cart_item/:id', to: "carts#delete_cart_item", as: "delete_cart_item"

  get 'orders_all', to: "orders#orders_all"
  patch '/update_status/:id', to: "orders#update_status", as: "update_status"

  resources :labels, only: [:new, :create, :destroy]
  resources :artists, only: [:new, :create, :destroy]
  resources :genres, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  acts_as_paranoid

  has_many :carts,     							 dependent: :destroy
  has_many :orders, through: :carts, dependent: :destroy
  has_many :favorites
  has_many :items, through: :favorites
  enum gender: {man: 1, woman: 2 }

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :japanese_syllabaries, presence: true, length: { maximum: 30}
  # validates :gender, acceptance: true
  validates :post_code, presence: true, length: { maximum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 13}

  has_many :receivers, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :receivers, reject_if: :all_blank, allow_destroy: true


  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new

      redirect_to root_path
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)

				Cart.create!(user_id: current_user.id)
		    Receiver.create!(user_id: current_user.id,
		    					receiver_name: current_user.name,
		    		 receiver_post_code: current_user.post_code,
		    			 receiver_address: current_user.address,
		    	receiver_phone_number: current_user.phone_number)
					
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      # respond_with resource
      flash[:sign_up_error] = resource.errors.full_messages
      flash[:sign_up] = resource.attributes
      redirect_to root_path
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

	def current_cart
		@cart = current_user.carts.last
	end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :admin_user, only: [:index, :destroy]
	before_action :correct_user, only: [:show, :receivers, :edit, :edit_receivers, :update]

	before_action :set_user, only: [:show, :receivers, :edit, :edit_receivers, :update, :destroy]

	def index
		@users = User.search(params[:search])
	end

	def show
	end

	def receivers
	end

	def edit
	end

	def edit_receivers
	end

	def update
		path = Rails.application.routes.recognize_path(request.referer)

		if @user.update(user_params)
			redirect_to user_path(@user.id)
		else
			if path[:edit]
				render :edit
			else path[:edit_receivers]
				render :edit_receivers
			end
		end
	end

	def destroy
		@user.destroy
		redirect_to users_path
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :japanese_syllabaries, :gender, :post_code, :address, :phone_number, :email, :birthday, :reviewer_name,
																	receivers_attributes: [:id, :receiver_name, :receiver_post_code, :receiver_address, :receiver_phone_number, :_destroy])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_receiver_fields.html.erb
<!-- receivers/editのcocoonによるrender先 -->

	<div class="nested-fields form-inline">
		<div class="form-group center-block">
    	<%= f.text_field :receiver_name %>
    	<%= f.text_field :receiver_post_code %>
    	<%= f.text_field :receiver_address %>
    	<%= f.text_field :receiver_phone_number %>
		</div>
    <%= link_to_remove_association "remove receiver", f %>
  </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 clearfix">
      <div class="edit-info">
        <h2 class="info">User information editing</h2>
      </div>

      <div class="edit-container">
        <div id="edit-detail">
          <%= form_for(@user) do |f| %>
            <div class="userbox">
              <%= f.label :name %>
              <%= f.text_field :name %>
            </div>

            <div class="userbox">
              <%= f.label :japanese_syllabaries %>
              <%= f.text_field :japanese_syllabaries %>
            </div>

            <div class="userbox">
              <%= f.label :gender %>
              <%= f.label :man %>
              <%= f.radio_button :gender, :man, class:"gender" %>
              <%= f.label :woman %>
              <%= f.radio_button :gender, :woman, class:"gender" %>
            </div>

            <div class="userbox">
              <%= f.label :post_code %>
              <%= f.text_field :post_code %>
            </div>

            <div class="userbox">
              <%= f.label :address %>
              <%= f.text_field :address %>
            </div>

            <div class="userbox">
              <%= f.label :phone_number %>
              <%= f.telephone_field :phone_number %>
            </div>

            <div class="userbox">
              <%= f.label :email %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"email" %>
            </div>

            <div class="userbox">
              <%= f.label :birthday %>
              <%= f.date_select(
                    :birthday,
                    start_year: 1930,
                    end_year:   (Time.now.year - 18),
                    default:    Date.new(1989, 1, 1)) %>
            </div>

            <div class="userbox">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <%= f.password_field :password, autocomplete: "new-password", class:"password" %>
            </div>

            <div class="userbox">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"password_confirm" %>
            </div>

            <div class="user-update">
              <%= f.submit "Update Account", class: "btn-default" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_receivers.html.erb
<!-- Receiver内容の編集画面 -->
<div class="container">
  <div class="row">

    <div class="col-md-10 col-md-offset-1 clearfix">
    	<h1>Edit Receivers</h1>
		</div>

		<div class="col-md-8 col-md-offset-2 clearfix">
			<label>Receiver Name</label>
			<label style="margin-left:80px" >Post Code</label>
			<label style="margin-left:110px">Address</label>
			<label style="margin-left:120px">Phone Number</label>
<!-- cocoon -->
  		<%= form_for(@user) do |f| %>
				<div class="field">
			  	<%= f.fields_for :receivers do |r| %>
			    	<%= render 'receiver_fields', f: r %>
			  	<% end %>
				</div>

				<div class="field">
			  	<%= link_to_add_association 'Receiver +', f, :receivers,
			  		data: { association_insertion_method: 'before' },
			  		class: "btn-default" %>
				</div>

				<%= f.submit 'Update Receiver', class: "btn-default" %>
			<% end %>
<!-- cocoon -->
	  	<div class="back-mypage">
	    	<%= link_to 'Back', :back %>
	  	</div>
		</div>

	</div>
</div>

app/views/users/index.html.erb
<div class="admin">
<h2>User Index</h2>
<div class="search">
<%= form_tag users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
</div>

<table class="table table-hover">
	<thead>
		<tr>
			<th>User name</th>
			<th>Japanese_syllabaries</th>
			<th>Address</th>
			<th>Email</th>
			<th>Phone_number</th>
			<th></th>

		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= link_to user.name, user_path(user) %></td>
			<td><%= user.japanese_syllabaries %></td>
			<td><%= user.address %></td>
			<td><%= user.email %></td>
			<td><%= user.phone_number %></td>
			<td><%= link_to "Destroy", user_path(user), method: :delete, "data-confirm" => "本当に消しますか?" %></td>

		</tr>
		<% end %>

	</tbody>
</table>
</div>

app/views/users/receiver.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 clearfix">

			<h1>Receivers</h1>
			<%= link_to "Edit", edit_user_receivers_path(@user), class: "btn-sm btn-success" %>
			<table class="table table-hover">
			  <thead>
			  	<tr>
			      <th>Receiver Name</th>
			      <th>Post Code</th>
			      <th>Address</th>
			      <th>Phone Number</th>
			    </tr>
			  </thead>
			  <tbody>
					<% @user.receivers.each do |receiver| %>
			  		<tr>
							<td><%= receiver.receiver_name %></td>
							<td><%= receiver.receiver_post_code %></td>
							<td><%= receiver.receiver_address %></td>
							<td><%= receiver.receiver_phone_number %></td>
						</tr>
					<% end %>
			  </tbody>
			</table>

		</div>
	</div>
</div>

app/views/users/receivers.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 clearfix">

			<h1>Receivers</h1>
			<%= link_to "Edit", edit_user_receivers_path(@user), class: "btn-default" %>
			<table class="table table-hover">
			  <thead>
			  	<tr>
			      <th>Receiver Name</th>
			      <th>Post Code</th>
			      <th>Address</th>
			      <th>Phone Number</th>
			    </tr>
			  </thead>
			  <tbody>
					<% @user.receivers.each do |receiver| %>
			  		<tr>
							<td><%= receiver.receiver_name %></td>
							<td><%= receiver.receiver_post_code %></td>
							<td><%= receiver.receiver_address %></td>
							<td><%= receiver.receiver_phone_number %></td>
						</tr>
					<% end %>
			  </tbody>
			</table>

		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 clearfix">


	    	<h2><%= @user.name %>'s page</h2>
	    	 <table class="table">
	    	 	<tr>
	    	 		<th>Japanese_syllabaries</th>
	    	 		<td><%= @user.japanese_syllabaries %></td>
	    	 	</tr>
					<tr>
						<th>Gender</th>
						<td><%= @user.gender %></td>
					</tr>
					<tr>
						<th>Post_code</th>
						<td><%= @user.post_code %></td>
					</tr>
					<tr>
						<th>Address</th>
						<td><%= @user.address %></td>
					</tr>
					<tr>
						<th>Email</th>
						<td><%= @user.email %></td>
					</tr>
					<tr>
						<th>Phone_number</th>
						<td><%= @user.phone_number %></td>
					</tr>
					<tr>
						<th>Birthday</th>
						<td><%= @user.birthday %></td>
					</tr>
				</table>

				<div class="btn-content clearfix">
					<div class="mypage-btn">
						<%= link_to "Purchase History", user_orders_path(@user), class: "btn" %>
					</div>
					<div class="mypage-btn">
						<%= link_to "User Edit", edit_user_path(@user), class: "btn" %>
					</div>
					<div class="mypage-btn">
						<%= link_to "Favorite", user_favorites_path(@user), class: "btn" %>
					</div>
					<div class="mypage-btn">
						<%= link_to "Unsubscribe", user_path(@user), method: :delete,  "data-confirm" => " Are you sure?", class: "btn"  %>
					</div>
					<div class="mypage-btn">
						<%= link_to "Add Receivers", user_receivers_path(@user), class: "btn" %>
					</div>
				</div>
			</div>

		    </div>
		</div>
	</div>
</div>