config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	        sessions: 'users/sessions',
	        registrations: 'users/registrations'
	      }
  resources :users do
    resource :favorites, only: [:show]
		resources :carts, only: [:show]
		resources :orders, only: [:index, :show, :new, :create]
  end
	get 'users/:id/receivers', to: 'users#receivers', as: "user_receivers"
  get 'users/:id/edit_receivers', to: 'users#edit_receivers', as: "edit_user_receivers"

  get 'contacts/about', to: 'contacts#about'
  get 'contacts/term', to: 'contacts#term'
  get 'contacts/recieve', to: 'contacts#recieve'
  resources :contacts

  root 'items#top'
  get 'items/about', to: 'items#about'
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  post '/add_cart_item/:item_id', to: "carts#add_cart_item", as: "add_cart_item"
  patch  '/update_cart_item/:id', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/delete_cart_item/:id', to: "carts#delete_cart_item", as: "delete_cart_item"

  get 'orders_all', to: "orders#orders_all"
  patch '/update_status/:id', to: "orders#update_status", as: "update_status"

  resources :labels, only: [:new, :create, :destroy]
  resources :artists, only: [:new, :create, :destroy]
  resources :genres, only: [:new, :create, :destroy]
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :music_names
	has_many :items
end

app/models/buy_datum.rb
class BuyDatum < ApplicationRecord
	belongs_to :cart_item
	
	attachment :buy_item_image
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_one    :order, 			dependent: :destroy
	has_many   :cart_items, dependent: :destroy

	validates :user, presence: true

	paginates_per 10
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :cart
	has_one :buy_datum, dependent: :destroy

	validates :item, presence: true
	validates :cart, presence: true
	validates :quantity, presence: true

	paginates_per 10
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :item

	has_many :music_names, inverse_of: :disc
	accepts_nested_attributes_for :music_names, reject_if: :all_blank, allow_destroy: true

	validates :item, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :item

	validates :user_id, presence: true
	validates :item_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :music_names
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :item_image


	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
	has_many :favorites
	has_many :users, through: :favorites
	has_many :cart_items,  dependent: :destroy
	has_many :reviews,     dependent: :destroy
	belongs_to :label
	belongs_to :artist
	belongs_to :genre

	has_many :discs, dependent: :destroy, inverse_of: :item
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	validates :label, presence: true
	validates :item_name, presence: true
	validates :price, presence: true
	validates :release_date, presence: true
	validates :stock, presence: true

	def self.search(search)
    if search
      Item.where(['item_name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/label.rb
class Label < ApplicationRecord
	has_many :items
end

app/models/music_name.rb
class MusicName < ApplicationRecord

	belongs_to :disc
	belongs_to :genre
	belongs_to :artist

	validates :genre,  presence: true
	validates :artist, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :receiver
	belongs_to :cart

	validates :cart, presence: true
	# validates :receiver, presence: true
	validates :grand_total, presence: true
	validates :payment_method, presence: true

	enum payment_method: {credit_card: 0, cash_on_delivery: 1, others: 2}
	enum status: {in_preparation: 0, sent: 1, delivered: 2}
end

app/models/receiver.rb
class Receiver < ApplicationRecord
	belongs_to :user
	has_many :orders

	validates :receiver_name, presence: true
	validates :receiver_post_code, presence: true
	validates :receiver_address, presence: true
	validates :receiver_phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :item
	validates :item, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  acts_as_paranoid

  has_many :carts,     							 dependent: :destroy
  has_many :orders, through: :carts, dependent: :destroy
  has_many :favorites
  has_many :items, through: :favorites
  enum gender: {man: 1, woman: 2 }

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :japanese_syllabaries, presence: true, length: { maximum: 30}
  # validates :gender, acceptance: true
  validates :post_code, presence: true, length: { maximum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 13}

  has_many :receivers, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :receivers, reject_if: :all_blank, allow_destroy: true


  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :correct_user_cart, only: [:show]
  before_action :set_cart_item, only: [:update_cart_item, :delete_cart_item]

  def show
  	@cart_items = current_cart.cart_items.page(params[:page])
    @grand_total = @cart_items.map { |a| a.item.price * a.quantity }.inject(:+)
  end

  def add_cart_item
		@cart_item = current_cart.cart_items.find_by(item_id: params[:item_id])
  	if @cart_item.blank?
  		@cart_item = current_cart.cart_items.build(item_id: params[:item_id])
  	end
  	@cart_item.quantity += cart_item_params[:quantity].to_i
  	@cart_item.save
  	redirect_to user_cart_path(current_user, current_cart)
  end

  def update_cart_item
    @cart_item.update!(cart_item_params)
  	@cart_item.save
  	redirect_to user_cart_path(current_user, current_cart)
  end

  def delete_cart_item
  	@cart_item.destroy
  	redirect_to user_cart_path(current_user, current_cart)
  end

  private

	def correct_user_cart
		unless user_signed_in? &&
			 		 params[:user_id].to_i == current_user.id &&
					 params[:id].to_i == current_cart.id
			flash[:alert] = "You don't have permission"
			redirect_to root_path
			return
		end
	end

  def set_cart_item
  	@cart_item = current_cart.cart_items.find(params[:id])
		if @cart_item.nil?
			flash[:alert] = "You don't have permission"
			redirect_to root_path
			return
		end
  end

	def cart_item_params
		params.require(:cart_item).permit(:quantity)
	end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
  	<div id="cart">
  		<h1>Cart</h1>
  	</div>

		<% if @cart_items.blank? %>
			<div class="col-xs-12">
				<strong class="empty-m">Your cart is empty</strong>
			</div>
		<% else %>
			<div class="col-xs-9">
				<table class="table table-hover table-condensed">
	        <thead>
	          <tr>
	            <th>Release date</th>
	            <th>Details</th>
	            <th>Quantity</th>
	            <th></th>
	          </tr>
	        </thead>
	        <tbody>
	          <% @cart_items.each do |cart_item| %>
	            <tr>
	              <td><%= cart_item.item.release_date %></td>
	              <td><%= link_to (attachment_image_tag cart_item.item, :item_image, :fill, 100, 100,
	              class: "pull-left profile-thumb cart-img", fallback: "no_image_big.jpg", alt: "Item Image"),
								item_path(cart_item.item) %>
	              <%= link_to cart_item.item.item_name, item_path(cart_item.item) %></td>
	              <td>
	              ¥<%= cart_item.item.price %></td>
	              <td>
	                <% if cart_item.item.stock != 0 %>
	                  <%= form_for(cart_item, url: update_cart_item_path(cart_item), method: :patch ) do |f| %>
	                    <%= f.number_field :quantity, min: 1, max: cart_item.item.stock, onchange: "submit(this.form)", class: "form-control" %>
	                  <% end %>
	                <% else %>
	                  <p>It's out of stock</p>
	                <% end %>
	              </td>
	              <td>
	                <%= link_to "", delete_cart_item_path(cart_item), method: :delete,
	                class: "glyphicon glyphicon-trash", style: "font-size: 20px" %>
	              </td>
	            </tr>
	          <% end %>
	        </tbody>
	      </table>
			</div>
			<div class="col-xs-3">
				<div class="panel panel-dafault">
					<p class="text-center">
						<strong>Grand Total</strong> : ¥<%= @grand_total %></p>
					<p class="text-center">
						<%= link_to "Checkout", new_user_order_path(current_user), class: "btn-default" %></p>
	      </div>
				<div class="">
	        <%= paginate @cart_items, class: "pagenate" %>
	      </div>
			</div>
		<% end %>
  </div>
</div>