config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	        sessions: 'users/sessions',
	        registrations: 'users/registrations'
	      }
  resources :users do
    resource :favorites, only: [:show]
		resources :carts, only: [:show]
		resources :orders, only: [:index, :show, :new, :create]
  end
	get 'users/:id/receivers', to: 'users#receivers', as: "user_receivers"
  get 'users/:id/edit_receivers', to: 'users#edit_receivers', as: "edit_user_receivers"

  get 'contacts/about', to: 'contacts#about'
  get 'contacts/term', to: 'contacts#term'
  get 'contacts/recieve', to: 'contacts#recieve'
  resources :contacts

  root 'items#top'
  get 'items/about', to: 'items#about'
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  post '/add_cart_item/:item_id', to: "carts#add_cart_item", as: "add_cart_item"
  patch  '/update_cart_item/:id', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/delete_cart_item/:id', to: "carts#delete_cart_item", as: "delete_cart_item"

  get 'orders_all', to: "orders#orders_all"
  patch '/update_status/:id', to: "orders#update_status", as: "update_status"

  resources :labels, only: [:new, :create, :destroy]
  resources :artists, only: [:new, :create, :destroy]
  resources :genres, only: [:new, :create, :destroy]
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :music_names
	has_many :items
end

app/models/buy_datum.rb
class BuyDatum < ApplicationRecord
	belongs_to :cart_item
	
	attachment :buy_item_image
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_one    :order, 			dependent: :destroy
	has_many   :cart_items, dependent: :destroy

	validates :user, presence: true

	paginates_per 10
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :cart
	has_one :buy_datum, dependent: :destroy

	validates :item, presence: true
	validates :cart, presence: true
	validates :quantity, presence: true

	paginates_per 10
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :item

	has_many :music_names, inverse_of: :disc
	accepts_nested_attributes_for :music_names, reject_if: :all_blank, allow_destroy: true

	validates :item, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :item

	validates :user_id, presence: true
	validates :item_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :music_names
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :item_image


	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
	has_many :favorites
	has_many :users, through: :favorites
	has_many :cart_items,  dependent: :destroy
	has_many :reviews,     dependent: :destroy
	belongs_to :label
	belongs_to :artist
	belongs_to :genre

	has_many :discs, dependent: :destroy, inverse_of: :item
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	validates :label, presence: true
	validates :item_name, presence: true
	validates :price, presence: true
	validates :release_date, presence: true
	validates :stock, presence: true

	def self.search(search)
    if search
      Item.where(['item_name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/label.rb
class Label < ApplicationRecord
	has_many :items
end

app/models/music_name.rb
class MusicName < ApplicationRecord

	belongs_to :disc
	belongs_to :genre
	belongs_to :artist

	validates :genre,  presence: true
	validates :artist, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :receiver
	belongs_to :cart

	validates :cart, presence: true
	# validates :receiver, presence: true
	validates :grand_total, presence: true
	validates :payment_method, presence: true

	enum payment_method: {credit_card: 0, cash_on_delivery: 1, others: 2}
	enum status: {in_preparation: 0, sent: 1, delivered: 2}
end

app/models/receiver.rb
class Receiver < ApplicationRecord
	belongs_to :user
	has_many :orders

	validates :receiver_name, presence: true
	validates :receiver_post_code, presence: true
	validates :receiver_address, presence: true
	validates :receiver_phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :item
	validates :item, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  acts_as_paranoid

  has_many :carts,     							 dependent: :destroy
  has_many :orders, through: :carts, dependent: :destroy
  has_many :favorites
  has_many :items, through: :favorites
  enum gender: {man: 1, woman: 2 }

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :japanese_syllabaries, presence: true, length: { maximum: 30}
  # validates :gender, acceptance: true
  validates :post_code, presence: true, length: { maximum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 13}

  has_many :receivers, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :receivers, reject_if: :all_blank, allow_destroy: true


  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

	def top
		@items_monthly = Item.all.sort_by{ |k, v| k.monthly_sales }.reverse.take(5)
		@items_weekly = Item.all.sort_by{ |k, v| k.weekly_sales }.reverse.take(5)
	end

	def about
	end

	def show
		@item = Item.find(params[:id])

		@review = Review.new
		@reviews = @item.reviews.page(params[:page])

		if user_signed_in? && !current_user.admin?
			if @cart_item.blank?
				@cart_item = current_cart.cart_items.build(item_id: params[:item_id])
			end

			if current_cart.cart_items.find_by(item_id: @item.id)
				@cart_item_quantity = current_cart.cart_items.find_by(item_id: @item.id).quantity
			else
				@cart_item_quantity = 0
			end
		end
	end

	def new
		@item = Item.new

		@label = Label.new
		@labels = Label.all

		@artist = Artist.new
		@artists = Artist.all

		@genre = Genre.new
		@genres = Genre.all

		@disc = @item.discs.build
		@music_name = @disc.music_names.build
	end

	def create
		@item = Item.new(item_params)
		if @item.save
			redirect_to items_path
		else
			@label = Label.new
			@labels = Label.all

			@artist = Artist.new
			@artists = Artist.all

			@genre = Genre.new
			@genres = Genre.all
			render :new
		end
	end

	def index
		@items = Item.search(params[:search])

		@items = @items.page(params[:page])
	end

	def edit
		@item = Item.find(params[:id])
		@labels = Label.all
		@artists = Artist.all
		@genres = Genre.all
	end

	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			redirect_to item_path(@item.id)
		else
			@item = Item.find(params[:id])
			@labels = Label.all
			@artists = Artist.all
			@genres = Genre.all
			render :edit
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to items_path
	end

	private

	def item_params
  	params.require(:item).permit(:label_id, :artist_id, :genre_id, :item_name, :item_image, :price, :stock, :release_date, :opinion,
  															 discs_attributes: [:id, :disc_name, :_destroy,
  															 music_names_attributes: [:id, :music_name, :artist_id, :genre_id, :_destroy]])
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_disc_fields.html.erb
<!-- items/newのcocoonによるrender先 -->

	<div class="nested-fields form-inline" style="margin-top:20px;">
		<div class=form-group>
			<%= f.label :disc_name %>
    	<%= f.text_field :disc_name %>
		</div>
    	<%= link_to_remove_association "remove disc", f %>

		<div class="music_names">
    	<%= f.fields_for :music_names do |m| %>
      	<%= render 'music_name_fields', f: m %>
    	<%end%>

			<div class="links">
	      <%= link_to_add_association "add music_name", f, :music_names %>
	    </div>

		</div>
  </div>

app/views/items/_music_name_fields.html.erb
<!-- items/_disc_fields.html.erbのcocoonによるrender先 -->

<div class="nested-fields form-inline" style="margin-top: 15px;">
  <div class="form-group">

			<label>Artist</label>
			<%= f.select :artist_id, @artists.map { |t| [t.artist_name, t.id] } %>

			<label>Genre</label>
			<%= f.select :genre_id, @genres.map { |t| [t.genre_name, t.id] } %>

    	<%= f.label :music_name %>
    	<%= f.text_field :music_name %>
  		
  		<%= link_to_remove_association "remove music_name", f %>

  </div>
</div>

app/views/items/about.html.erb

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
    	<div id="about">
    		<h1>SERVICE</h1>

    		<div class="about-title">
    			<h4> How to use</h4>
    			<p class="about-guide">
    				We are offering various professional mode services with "client problem solving" as a mission.<br>
			   		In the "partner style" to meet the needs firmly headed to the client at the tortillas and spots,<br>
			   		We are accelerating the client's business and earning reliable trust and support.
		   	  </p>
		   		<p class="about-text"></p>
		   	</div>
		   	<hr>
		  </div>
		</div>
	</div>
</div>

<div class="video">
	<video controls autoplay loop>
		<source src="/assets/demo.mp4">
			<P>Sorry, your browser doesn't support embedded videos.</P>
		</video>
 </div>



app/views/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
			<h1><%= @item.item_name %></h1>

<!-- エラー文 -->
			<% if @item.errors.any? %>
	      <div class="error-explanation">
	        <h2><%= @item.errors.count %>errors occured</h2>
	        <ul>
	          <% @item.errors.full_messages.each do |message| %>
	            <li><%= message %></li>
	          <% end %>
	        </ul>
	      </div>
	    <% end %>
<!-- エラー文 -->

			<%= form_for(@item) do |f| %>
			<ul style=" list-style: none;">
				<li>
					<label>Single/Album name</label>
					<%= f.text_field :item_name, class: "col-xs-12 book_title" %>
				</li>
				<li>
					<label>Cover Image</label>
					<%= f.attachment_field :item_image %>
				</li>
				<li>
					<label>Release</label>
					<%= f.date_select(
        	:release_date,
        	start_year: 1980,
        	end_year:   (Time.now.year),
        	default:    Date.new(Time.now.year, 1, 1)) %>
				</li>
				<li>
					<label>Price</label>
					<%= f.text_field :price, class: "col-xs-12" %>
				</li>
				<li>
					<label>Stock</label>
					<%= f.text_field :stock, class: "col-xs-12" %>
				</li>
				<li>
					<label>Label_name</label>
					<%= f.select :label_id, @labels.map { |t| [t.label_name, t.id] } %>
				</li>

				<li>
					<label>Artist_name</label>
					<%= f.select :artist_id, @artists.map { |t| [t.artist_name, t.id] } %>
				</li>

				<li>
					<label>Genre_name</label>
					<%= f.select :genre_id, @genres.map { |t| [t.genre_name, t.id] } %>
				</li>
				<li>
					<label>Opinion</label>
					<%= f.text_area :opinion, class: "col-xs-12" %>
				</li>

<!-- cocoon -->

				<li>
					<label>Discs</label>
					<div class="field">
				    <%= f.fields_for :discs do |d| %>
				      <%= render 'disc_fields', f: d %>
				    <% end %>
				  </div>

				  <div class="field">
				  	<%= link_to_add_association 'Disc +', f, :discs,
				  		data: { association_insertion_method: 'before' },
				  		class: "btn-md btn-default" %>
				  </div>
				</li>

<!-- cocoon -->

				<li style="margin-top: 10px;">
					<%= f.submit 'Update Item', class: "btn-default" %>
				</li>
			</ul>
			<% end %>

			<%= link_to 'Back', item_path(@item) %>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>商品検索</h2>

      <%= form_tag items_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :item_name => nil %>
      </p>
      <% end %>
      

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Release Date</th>
            <th></th>
            <th>Single/Album name</th>
            <th>Label</th>
            <th>Artist</th>
            <th>Genre</th>
            <th>Price</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
              <tr>
                <td>
                  <%= item.release_date %>
                </td>
                <td>
                  <%= link_to item_path(item) do %>
                    <%= attachment_image_tag item, :item_image, :fill, 40, 40, fallback: "no_image_small.jpg", alt:"Cover image"%>
                  <% end %>
                </td>
                <td>
                  <%= link_to item.item_name, item_path(item) %>
                </td>
                <td>
                  <%= item.label.label_name %>
                </td>
                <td>
                  <%= item.artist.artist_name %>
                </td>
                <td>
                  <%= item.genre.genre_name %>
                </td>
                <td>
                  <p>￥<%= item.price %></p>
                </td>
                <td>
                  <% if item.stock == 0 %>
                    <p style="color: red;">Sold Out!!</p>
                  <% else %>
                    <p>Stock: <%= item.stock %></p>
                  <% end %>
                </td>
                
                <% if user_signed_in? && current_user.admin? %>
                  <td>
                    <%= link_to "Edit", edit_item_path(item), class: "btn-sm btn-success" %>
                  </td>
                  
                  <td>
                    <%= link_to "Destroy", item_path(item), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか?" %>
                  </td>
                <% end %>
              </tr>
          <% end %>
        <tbody>
      </table>

    <%= paginate @items, class: "pagenate" %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
			<h1>New Item</h1>
<!-- エラー文 -->
			<% if @item.errors.any? %>
	      <div class="error-explanation">
	        <h2><%= @item.errors.count %>件のエラーが発生しました。</h2>
	        <ul>
	          <% @item.errors.full_messages.each do |message| %>
	            <li><%= message %></li>
	          <% end %>
	        </ul>
	      </div>
	    <% end %>
<!-- エラー文 -->


<!-- モーダル -->
			<div id="modal-label" class="btn btn-md btn-primary"  >New Label</div>
      <%= render "labels/new_modal" %>
			<div id="modal-artist" class="btn btn-md btn-primary" >New Artist</div>
      <%= render "artists/new_modal" %>
			<div id="modal-genre" class="btn btn-md btn-primary"  >New Genre</div>
      <%= render "genres/new_modal" %>
<!-- form要素の中にモーダルを入れてしまうと、モーダル上でのsubmitが
	formのsubmitと認識されてしまう→モーダルをform要素外に出している -->
<!-- モーダル -->

			<%= form_for(@item) do |f| %>

				<ul style="margin-top: 10px; list-style: none;">
					<li>
						<label>Single/Album name</label>
						<%= f.text_field :item_name %>
					</li>

					<li>
						<label>Cover Image</label>
						<%= f.attachment_field :item_image %>
					</li>

					<li>
						<label>Release date</label>
						<%= f.date_select(
          	:release_date,
          	start_year: 1980,
          	end_year:   (Time.now.year),
          	default:    Date.new(Time.now.year, 1, 1)) %>
					</li>

					<li>
						<%= f.label :price %>
						<%= f.number_field :price %>
					</li>

					<li>
						<%= f.label :stock %>
						<%= f.number_field :stock %>
					</li>

					<li>
						<label>Label_name</label>
						<%= f.select :label_id, @labels.map { |t| [t.label_name, t.id] } %>
					</li>

					<li>
						<label>Artist_name</label>
						<%= f.select :artist_id, @artists.map { |t| [t.artist_name, t.id] } %>
					</li>

					<li>
						<label>Genre_name</label>
						<%= f.select :genre_id, @genres.map { |t| [t.genre_name, t.id] } %>
					</li>

					<li>
						<div>
							<%= f.label :opinion, style: "float:left;" %>
						</div>
						<div>
							<%= f.text_area :opinion, style: "float:left; margin-left: 15px;" %>
						</div>
					</li>

<!-- cocoon -->

					<li>
						<div class="field">
					    <%= f.fields_for :discs do |d| %>
					      <%= render 'disc_fields', f: d %>
					    <% end %>
					  </div>

					  <div style="margin-top: 10px;" class="field">
					  	<%= link_to_add_association 'Disc +', f, :discs,
					  		data: { association_insertion_method: 'before' },
					  		class: "btn-lg btn-primary" %>
					  </div>
					</li>

<!-- cocoon -->
				</ul>
				<%= f.submit 'Create Item', class: "item_create" %>
			<% end %>
    </div>  
  </div>
</div>

app/views/items/show.html.erb
<div class="container details-main">
  <div class="row">

    <div class="col-md-3">
      <div class="cd-image">
        <%= attachment_image_tag @item,:item_image, :fill, 100, 100, class: "col-md-12 pull-left profile-thumb ", fallback: "no_image_big.jpg", alt: "Item Image" %>
      </div>
      <div class="cd-price">
        <p>￥ <%= @item.price %></p>
      </div>
      <div class="opinion-box">
        <h3 class="o-title">Opnion</h3>
        <p><%= @item.opinion %></p>
      </div>
    </div>

    <div class="col-md-6">
      <div class="item-name-box">
        <h3 class="item-name"><%= @item.item_name %></h3>
      </div>
        <div id="item-detail-box">
          <dl>
            <dt>Artist:</dt>
            <dd><%= @item.artist.artist_name %></dd>

            <dt>Genre:</dt>
            <dd><%= @item.genre.genre_name %></dd>

            <dt>Label:</dt>
            <dd><%= @item.label.label_name %></dd>

            <dt>Release_date:</dt>
            <dd><%= @item.release_date %></dd>
          </dl>
        </div>

        <% @item.discs.each do |disc| %>
          <p class="main-disc-name"><%= disc.disc_name %></p>
            <table id="cd-detail-box">
              <tr>
                <th>Music Name</th>
                <th>Artist</th>
                <th>Genre</th>
              </tr>
              <% disc.music_names.each do |music| %>
              <tr>
                <td><%= music.music_name %></td>
                <td><%= music.artist.artist_name %></td>
                <td><%= music.genre.genre_name %></td>
              </tr>
              <% end %>
            </table>
        <% end %>
      </div>

    <div class="col-md-3">
      <div class="ready-order-box">
        <div class="ready-order">
          <p class="item-stock">Item Stock: <%= @item.stock %></p>

          <% if user_signed_in? && !current_user.admin? %>
          <div>
            <% if @item.stock == 0 %>
              <p>It's out of stock</p>
            <% elsif @item.stock == @cart_item_quantity %>
              <p>Can not add any more</p>
            <% else %>
              <%= form_for(@cart_item, url: add_cart_item_path(@item.id) ) do |f| %>
                <p class="item-stock">Quantity:</p>
                <%= f.select :quantity, [*1..@item.stock - @cart_item_quantity] %>
                <%= f.submit "Add to cart", class: "btn-cart" %>
              <% end %>
            <% end %>
          <% end %>
      </div>

      <% if user_signed_in? && current_user.admin? %>
        <div>
        <%= link_to "Edit", edit_item_path(@item), class: "btn-lg btn-edit" %>
        <%= link_to "Destroy", item_path(@item), method: :delete, class: "btn-lg btn-des", "data-confirm" => "本当に消しますか?" %>
        </div>
      <% end %>

      <!-- favorite -->

      <% if user_signed_in? %>
        <% if @item.favorited_by?(current_user) %>
          <%= link_to item_favorites_path(@item), class: "btn-favorite col-xs-12", method: :delete do %>
            <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
            <%= @item.favorites.count %> favorit
          <% end %>
        <% else %>
          <%= link_to item_favorites_path(@item), class: "btn-favorite col-xs-12", method: :post do %>
            <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
            <%= @item.favorites.count %> favorit
          <% end %>
        <% end %>
      <% end %>

      <!-- favorite -->
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-2">
        <!-- review -->

      <div>
        <h4>ALL Rewiew</h4>
        <div id="reviews_area">
        <% @reviews.each do |review| %>
        <% unless review.id.nil? %>
        <p class="r-name">Reviewer：<%= review.reviewer_name %></p>
        <hr class="r-hr">
        <p class="r-text">Review：<%= review.review_text %></p>
        <hr class="r-hr">

        <p><%= link_to 'Comment Delete', item_reviews_path(item_id: review.item_id, review_id: review.id), method: :delete %>
        </p>
        <% end %>
        <% end %>
        </div>

        <h4>Rewiew</h4>
        <%= form_with(model: [@item, @review], local: true ) do |form| %>
            <div class="r-comment">
            <%= form.text_field :reviewer_name, :placeholder => "Your Name" %>
            </div>
            <div class="r-comment">
            <%= form.text_area :review_text, :placeholder => "Your Comment" %>
            </div class="r-comment">
            <div class="actions">
            <%= form.submit "Comment" %>
            </div>
        <% end %>
      </div>
      <%= paginate @reviews, class: "pagenate" %>
        <!-- review -->
    </div>
  </div>
</div>

app/views/items/top.html.erb
<!-- 自動スライドショー -->
<div class="in">
  <img src="assets/img/images1.jpg">
  <img src="assets/img/images2.jpg">
  <img src="assets/img/images3.jpg">
  <img src="assets/img/images4.jpg">
  <img src="assets/img/images5.jpg">
</div>

<p class="sub-nav"> PICK UP CONTENTS</p>

<!-- 手動スライドショー -->
<div class="slider-container">
  <div class="slider clearfix">
    <div><img src="assets/img/slider1.jpg"></div>
    <div><img src="assets/img/slider2.jpg"></div>
    <div><img src="assets/img/slider3.jpg"></div>
    <div><img src="assets/img/slider1.jpg"></div>
    <div><img src="assets/img/slider2.jpg"></div>
    <div><img src="assets/img/slider3.jpg"></div>
  </div>
</div>

<p class="sub-nav"> MUSE TOP10</p>
  <div class="local-navbox">
    <nav class="local-nav clearfix">
      <ul class="local-navbar">
        <li class="local-nav-item active"> Monthy</li>
        <li class="local-nav-item"> Weekly</li>
      </ul>
    </nav>

    <ul class="rnk-content">
      <li>
        <% n = 1 %>
        <% @items_monthly.each do |item| %>
          <div class="rnk-item-container clearfix">
            <hr>
            <div class="rnk-main">
              <div class="item-rnk">
                <div class="lank"><%= n %></div>
              </div>
              <div class="rnk-item-details">
                <%= attachment_image_tag item, :item_image %>

              </div>
              <div class="rnk-title">
                <p> <%= item.artist.artist_name %></p>
              </div>
              <div class="rnk-artist">
                <p><%= link_to item.item_name, item_path(item) %></p>
              </div>
            </div>
          </div>
        <% n += 1 %>
        <% end %>
      </li>

      <li class="hide">
        <% n = 1 %>
        <% @items_weekly.each do |item| %>
          <div class="rnk-item-container clearfix">
            <hr>
            <div class="rnk-main">
              <div class="item-rnk">
                <div class="lank"><%= n %></div>
              </div>
              <div class="rnk-item-details">
                <%= attachment_image_tag @item,:item_image, :fill, 100, 100, fallback: "no_image_big.jpg", alt: "Item Image" %>
              </div>
              <div class="rnk-title">
                <p><%= item.artist.artist_name %></p>
              </div>
              <div class="rnk-artist">
                <p><%= link_to item.item_name, item_path(item) %></p>
              </div>
            </div>
          </div>
        <% n += 1 %>
        <% end %>
      </li>
    </ul>
  </div>

<div id="play">
  <audio preload="auto" id="sound" src="/assets/chainsmokers.mp3" autoplay>
  </audio>
</div>