config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	        sessions: 'users/sessions',
	        registrations: 'users/registrations'
	      }
  resources :users do
    resource :favorites, only: [:show]
		resources :carts, only: [:show]
		resources :orders, only: [:index, :show, :new, :create]
  end
	get 'users/:id/receivers', to: 'users#receivers', as: "user_receivers"
  get 'users/:id/edit_receivers', to: 'users#edit_receivers', as: "edit_user_receivers"

  get 'contacts/about', to: 'contacts#about'
  get 'contacts/term', to: 'contacts#term'
  get 'contacts/recieve', to: 'contacts#recieve'
  resources :contacts

  root 'items#top'
  get 'items/about', to: 'items#about'
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  post '/add_cart_item/:item_id', to: "carts#add_cart_item", as: "add_cart_item"
  patch  '/update_cart_item/:id', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/delete_cart_item/:id', to: "carts#delete_cart_item", as: "delete_cart_item"

  get 'orders_all', to: "orders#orders_all"
  patch '/update_status/:id', to: "orders#update_status", as: "update_status"

  resources :labels, only: [:new, :create, :destroy]
  resources :artists, only: [:new, :create, :destroy]
  resources :genres, only: [:new, :create, :destroy]
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :music_names
	has_many :items
end

app/models/buy_datum.rb
class BuyDatum < ApplicationRecord
	belongs_to :cart_item
	
	attachment :buy_item_image
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_one    :order, 			dependent: :destroy
	has_many   :cart_items, dependent: :destroy

	validates :user, presence: true

	paginates_per 10
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :cart
	has_one :buy_datum, dependent: :destroy

	validates :item, presence: true
	validates :cart, presence: true
	validates :quantity, presence: true

	paginates_per 10
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :item

	has_many :music_names, inverse_of: :disc
	accepts_nested_attributes_for :music_names, reject_if: :all_blank, allow_destroy: true

	validates :item, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :item

	validates :user_id, presence: true
	validates :item_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :music_names
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :item_image


	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
	has_many :favorites
	has_many :users, through: :favorites
	has_many :cart_items,  dependent: :destroy
	has_many :reviews,     dependent: :destroy
	belongs_to :label
	belongs_to :artist
	belongs_to :genre

	has_many :discs, dependent: :destroy, inverse_of: :item
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	validates :label, presence: true
	validates :item_name, presence: true
	validates :price, presence: true
	validates :release_date, presence: true
	validates :stock, presence: true

	def self.search(search)
    if search
      Item.where(['item_name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/label.rb
class Label < ApplicationRecord
	has_many :items
end

app/models/music_name.rb
class MusicName < ApplicationRecord

	belongs_to :disc
	belongs_to :genre
	belongs_to :artist

	validates :genre,  presence: true
	validates :artist, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :receiver
	belongs_to :cart

	validates :cart, presence: true
	# validates :receiver, presence: true
	validates :grand_total, presence: true
	validates :payment_method, presence: true

	enum payment_method: {credit_card: 0, cash_on_delivery: 1, others: 2}
	enum status: {in_preparation: 0, sent: 1, delivered: 2}
end

app/models/receiver.rb
class Receiver < ApplicationRecord
	belongs_to :user
	has_many :orders

	validates :receiver_name, presence: true
	validates :receiver_post_code, presence: true
	validates :receiver_address, presence: true
	validates :receiver_phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :item
	validates :item, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  acts_as_paranoid

  has_many :carts,     							 dependent: :destroy
  has_many :orders, through: :carts, dependent: :destroy
  has_many :favorites
  has_many :items, through: :favorites
  enum gender: {man: 1, woman: 2 }

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :japanese_syllabaries, presence: true, length: { maximum: 30}
  # validates :gender, acceptance: true
  validates :post_code, presence: true, length: { maximum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 13}

  has_many :receivers, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :receivers, reject_if: :all_blank, allow_destroy: true


  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">

    <title>Muse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- slick -->
    <link rel="stylesheet" type="text/css" href="assets/slick.css"/>
    <link rel="stylesheet" type="text/css" href="assets/slick-theme.css"/>
    <script src="assets/slick.min.js"></script>

  </head>

  <body>

    <header>
      <div class="container">
          <nav class="globnav navbar-left">
            <span class="logo">MUSE.</span>
          </nav>

            <nav class="globnav navbar-right">
              <ul class="navbar-menu">

                <% if user_signed_in? && current_user.admin? %>

                <li class="header-nav-item">
                  <%= link_to "HOME", root_path %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "USERS", users_path %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "LIST", items_path %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "NEW", new_item_path %>
                </li>
								<li class="header-nav-item">
                  <%= link_to "ORDERS", orders_all_path %>
                </li>
                <li class="header-nav-item">
                   <%= link_to "LOG OUT" , destroy_user_session_path, method: :delete %>
                </li>


                <% elsif user_signed_in? %>


                <li class="header-nav-item">
                  <%= link_to "HOME", root_path %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "SERVICE", items_about_path %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "MY PAGE", user_path(current_user) %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "CART", user_cart_path(current_user, current_cart) %>
                </li>
                <li class="header-nav-item">
                   <%= link_to "LOG OUT" , destroy_user_session_path, method: :delete %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "SEARCH", items_path %>
                </li>
                <li class="header-nav-item">
                  <%= link_to 'Signed_in '+ current_user.name, user_path(current_user)  %>
                </li>

                <% else %>

                <li class="header-nav-item">
                 <%= link_to "HOME", root_path %>
                </li>
                <li class="header-nav-item">
                 <%= link_to "SERVICE", items_about_path %>
                </li>
                <li class="header-nav-item">
                  <a><div id="modal-sign-up"> SIGN UP</div></a>
                  <%= render "devise/registrations/registrations_modal" %>
                </li>
                <li class="header-nav-item">
                  <a><div id="modal-sign-in"> LOG IN</div></a>
                  <%= render "devise/sessions/sessions_modal" %>
                </li>
                <li class="header-nav-item">
                  <%= link_to "SEARCH", items_path %>
                </li>
                <% end %>
              </ul>
            </nav>
        </div>
    </header>

    <main>
    <% if flash[:sign_up_error] %>
      <%= flash[:sign_up_error] %>
      <p><%= flash[:sign_up_error].count %></p>
    <% else %>
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    <% end %>

        <%= yield %>

    </main>

    <footer>
      <div class="container">
        <nav class="globnav">
            <% if user_signed_in? && current_user.admin? %>

            <ul class="navbar-menu">
              <li class="footer-nav-item">
               <%= link_to "Contact", contacts_recieve_path%>
              </li>
              <li class="footer-nav-item">
               <a href="/users"> &#169; 2018 MUSE. </a>
              </li>

            </ul>

            <% else %>

            <ul class="navbar-menu">
              <li class="footer-nav-item">
                <%= link_to "PRIVACY POLICY", contacts_path %>
              </li>
              <li class="footer-nav-item">
                <%= link_to "ABOUT US", contacts_about_path %>
              </li>
              <li class="footer-nav-item">
                <%= link_to "TERMS OF USE", contacts_term_path %>
              </li>
              <li class="footer-nav-item">
                <%= link_to "CONTACT", new_contact_path %>
              </li>
              <li class="footer-nav-item">
               <a href="/users">&#169; 2018 MUSE.</a>
              </li>
            </ul>
            <% end %>

        </nav>
      </div>
    </footer>
  </body>
</html>